version: 2
executorType: machine
jobs:
  build:
    working_directory: ~/homebrew-linuxkit
    steps:
      - checkout
      - run: |
          brew update
          brew env
          brew config
          mkdir -p $(brew --repo)/Library/Taps/linuxkit
          ln -s ~/homebrew-linuxkit $(brew --repo)/Library/Taps/linuxkit/homebrew-linuxkit
          ./test.sh
