version: 2
executorType: machine
jobs:
  build:
    working_directory: ~/homebrew-linuxkit
    steps:
      - checkout
      - run: |
          brew update
          brew env
          brew config
          mkdir -p $(brew --repo)/Library/Taps/linuxkit
          ln -s ~/homebrew-linuxkit $(brew --repo)/Library/Taps/linuxkit/homebrew-linuxkit
          for pkg in "linuxkit" "moby" "rtf"; do
              brew install --HEAD $pkg --verbose
              # Skip audit until we have a stable download
              # brew audit $pkg --strict
              brew test $pkg
          done
